#!/usr/bin/env python3
"""
sync_ide.py — Antigravity Kit Multi-IDE Synchronization
Gera arquivos de configuração do kit para outros IDEs (Claude, Cursor, Codex).
Usage:
  python .agent/scripts/sync_ide.py --target claude
  python .agent/scripts/sync_ide.py --target cursor
  python .agent/scripts/sync_ide.py --target codex
  python .agent/scripts/sync_ide.py --target all
  python .agent/scripts/sync_ide.py --dry-run --target all
"""
import argparse
import sys
from pathlib import Path

# ── constants ─────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_DIR = REPO_ROOT / ".agent"
RULES_PATH = AGENT_DIR / "rules" / "GEMINI.md"
ARCHITECTURE_PATH = AGENT_DIR / "ARCHITECTURE.md"
AGENTS_DIR = AGENT_DIR / "agents"

GREEN = "\033[92m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"
BOLD = "\033[1m"


# ── helpers ───────────────────────────────────────────────────────────────────
def read_file_safe(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8", errors="ignore")
    return ""


def write_output(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"  {YELLOW}[DRY-RUN]{RESET} Would write: {path}")
        print(f"           ({len(content)} chars)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  {GREEN}✔{RESET} Written: {path}")


def build_agent_summary() -> str:
    """Build a compact summary of available agents for injection into IDE configs."""
    agents = sorted(AGENTS_DIR.glob("*.md")) if AGENTS_DIR.exists() else []
    if not agents:
        return ""
    lines = ["## Available Agents\n"]
    for agent_path in agents:
        content = agent_path.read_text(encoding="utf-8", errors="ignore")
        # Extract name and description from frontmatter
        name = ""
        description = ""
        for line in content.splitlines():
            if line.startswith("name:"):
                name = line.split(":", 1)[1].strip()
            elif line.startswith("description:"):
                description = line.split(":", 1)[1].strip()[:120]
            if name and description:
                break
        if name:
            lines.append(f"- **{name}**: {description}")
    return "\n".join(lines)


# ── target: claude ────────────────────────────────────────────────────────────
def generate_claude_config(dry_run: bool) -> None:
    """Generate .claude/CLAUDE.md with core rules from GEMINI.md."""
    print(f"\n{CYAN}{BOLD}→ Syncing: Claude Code{RESET}")

    gemini_content = read_file_safe(RULES_PATH)
    agent_summary = build_agent_summary()

    content = f"""# CLAUDE.md — Antigravity Kit Rules
> Auto-generated from .agent/rules/GEMINI.md. Do not edit manually — run sync_ide.py to update.

---

## How to Use Agents

Activate any specialist by mentioning them:
```
@agent-name your request here
```

{agent_summary}

---

## Core Rules (from GEMINI.md)

{gemini_content}
"""
    output_path = REPO_ROOT / ".claude" / "CLAUDE.md"
    write_output(output_path, content, dry_run)


# ── target: cursor ────────────────────────────────────────────────────────────
def generate_cursor_config(dry_run: bool) -> None:
    """Generate .cursor/rules.md with condensed ruleset for Cursor."""
    print(f"\n{CYAN}{BOLD}→ Syncing: Cursor{RESET}")

    gemini_content = read_file_safe(RULES_PATH)
    agent_summary = build_agent_summary()

    # Extract only TIER 0 and TIER 1 sections for Cursor (more concise)
    tier_content = gemini_content
    if "## TIER 0" in gemini_content:
        start = gemini_content.index("## TIER 0")
        tier_content = gemini_content[start:]

    content = f"""# Antigravity Kit — Cursor Rules
> Auto-generated from .agent/rules/GEMINI.md via sync_ide.py

{agent_summary}

---

{tier_content}
"""
    output_path = REPO_ROOT / ".cursor" / "rules.md"
    write_output(output_path, content, dry_run)


# ── target: codex ─────────────────────────────────────────────────────────────
def generate_codex_config(dry_run: bool) -> None:
    """Generate AGENTS.md (Codex CLI standard) with agent list and rules."""
    print(f"\n{CYAN}{BOLD}→ Syncing: Codex CLI{RESET}")

    agent_summary = build_agent_summary()
    gemini_content = read_file_safe(RULES_PATH)

    content = f"""# AGENTS.md — Antigravity Kit for Codex CLI
> Auto-generated by sync_ide.py. Do not edit manually.

This file configures the Antigravity Kit specialist agents for Codex CLI.

---

{agent_summary}

---

## Behavior Rules

{gemini_content}
"""
    output_path = REPO_ROOT / "AGENTS.md"
    write_output(output_path, content, dry_run)


# ── registry ──────────────────────────────────────────────────────────────────
TARGETS: dict[str, callable] = {
    "claude": generate_claude_config,
    "cursor": generate_cursor_config,
    "codex": generate_codex_config,
}


# ── main ──────────────────────────────────────────────────────────────────────
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync Antigravity Kit to other IDEs.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python .agent/scripts/sync_ide.py --target claude
  python .agent/scripts/sync_ide.py --target all
  python .agent/scripts/sync_ide.py --dry-run --target all
        """,
    )
    parser.add_argument(
        "--target",
        choices=[*TARGETS.keys(), "all"],
        required=True,
        help="IDE target to sync to (claude, cursor, codex, or all)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be written without modifying any files",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    mode = "DRY-RUN" if args.dry_run else "SYNC"
    print(f"\n{BOLD}🔄 Antigravity Kit — Multi-IDE Sync [{mode}]{RESET}")
    print("─" * 50)

    if not RULES_PATH.exists():
        print(f"\n  ✘ GEMINI.md not found at {RULES_PATH}")
        print("  Make sure you are running from the project root.")
        sys.exit(1)

    targets_to_run: list[str] = list(TARGETS.keys()) if args.target == "all" else [args.target]

    for target in targets_to_run:
        TARGETS[target](args.dry_run)

    print(f"\n{'─' * 50}")
    if args.dry_run:
        print(f"\n{YELLOW}{BOLD}[DRY-RUN] No files were modified.{RESET}\n")
    else:
        print(f"\n{GREEN}{BOLD}✅ Sync complete for: {', '.join(targets_to_run)}{RESET}\n")


if __name__ == "__main__":
    main()
